config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about'

  # resources :posts the following routes:
  #   => posts#index     (GET)
  #   => posts#create    (POST)
  #   => posts#new       (GET)
  #   => posts#edit      (GET)
  #   => posts#show      (GET)
  #   => posts#update    (PATCH)
  #   => posts#update    (PUT)
  #   => posts#destroy   (DELETE)
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    # Adding relationship with commments
    has_many :comments
    # Adding title validation
    validates :title, presence: true,
                        length: {minimum: 5}
    # Adding body validation
    validates :body,  presence: true,
                        length: {maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "basil", password: "letmein", only: [:destroy]

    def create
        @post = Post.find(params[:post_id])

        @comment = @post.comments.create(comment_params)
    
        redirect_to post_path(@post)
    end


    def destroy
        @post = Post.find(params[:id])
        Comment.find(params[:id]).destroy
        redirect_to post_path(@post)
    end

    private def comment_params
        params.require(:comments).permit(:username, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About Me';
        @content = 'This is the about page';
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    http_basic_authenticate_with name: "basil", password: "letmein", except: [:index, :show]

    def index
        @posts = Post.all

    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        # Pass the form data through an object of the Post model
        @post = Post.new(post_params)

        if(@post.save)
            # If the form validates and saves then redirect
            redirect_to @post
        else
            # If it doesn't then refresh the page
            render 'new'
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end

    def destroy
        Post.find(params[:id]).destroy
        
        redirect_to home_path
    end

    # Make sure that only title and body are passed through the form, and that they're required
    private def post_params
        params.require(:posts).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments-form.html.erb
<h4>Add Comment:</h4>
<%= form_for :comments, url: post_comments_path(@post) do |f| %>
    <p>
        <%= f.label :username, class: 'control-label' %><br>
        <%= f.text_field :username, class: 'form-control' %>
    </p>

    <p>
        <%= f.label :body, class: 'control-label' %>
        <%= f.text_area :body, class: 'form-control' %>
    </p>

    <p>
        <%= f.submit "Post Comment", class: 'btn btn-block btn-dark'  %>
    </p>
<% end %>

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="card flex-md-row mb-4 box-shadow">
        <div class="card-body d-flex flex-column align-items-start">
            <p><strong><%= comment.username %>:</strong> <%= comment.body%> </p>
            <%= link_to "Delete", [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?'}, class: 'text-danger' %>
        </div>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag     'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://use.fontawesome.com/releases/v5.0.8/js/all.js' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="<%= home_path %>">Simple Blog</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#"><i class="fas fa-search mr-3"></i></a>
            <a class="btn btn-sm btn-outline-secondary" href="<%= new_post_path %>"> <i class="fas fa-pencil-alt"></i> Write</a>
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-center">
            <p class="text-muted">
                Keeping it sleek and simple
            </p>
        </nav>
      </div>
      <main class="container">
            <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<p class="h2 lead">Edit Post</p>
<hr>
<div class="row">
    <div class="col">
        <%= form_for :posts, url: post_path(@post), method: :patch do |f| %>
            <% if @post.errors.any? %>
                <% @post.errors.full_messages.each do |msg| %>
                    <div class="alert alert-danger"><%= msg %></div>
                <% end %>
            <% end %>    
            <p>
                <%= f.label :title, class: 'control-label' %><br>
                <%= f.text_field :title, class: 'form-control', value: @post.title %>
            </p>

            <p>
                <%= f.label :body, class: 'control-label' %><br>
                <%= f.text_area :body, class: 'form-control', value: @post.body %>
            </p>

            <p>
                <%= f.submit "Save Post", class: 'btn btn-block btn-dark' %>
            </p>
        <% end %>
    </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="row mb-2">
        <div class="col">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                    <h3 class="mb-0">
                    <a class="text-dark" href="<%= post_path(post) %>"><%= post.title %></a>
                    </h3>
                    <div class="mb-1 text-muted"><%= post.created_at.to_formatted_s(:long_ordinal) %></div>
                    <p class="card-text mb-auto">
                        <%= post.body %>
                    </p>
                    <%= link_to "Read More", post_path(post), class: 'btn btn-large btn-dark' %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/posts/new.html.erb
<p class="h2 lead">Add Post</p>
<hr>
<div class="row">
    <div class="col">
        <%= form_for :posts, url: posts_path do |f| %>
            <% if @post.errors.any? %>
                <% @post.errors.full_messages.each do |msg| %>
                    <div class="alert alert-danger"><%= msg %></div>
                <% end %>
            <% end %>    
            <p>
                <%= f.label :title, class: 'control-label' %><br>
                <%= f.text_field :title, class: 'form-control' %>
            </p>

            <p>
                <%= f.label :body, class: 'control-label' %><br>
                <%= f.text_area :body, class: 'form-control' %>
            </p>

            <p>
                <%= f.submit "Save Post", class: 'btn btn-block btn-dark' %>
            </p>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="row mb-2">
    <div class="col">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <h2><%= @post.title %></h2>
                <p><%= @post.body %></p>          
            </div>
        </div>
        <%= link_to "Edit Post", edit_post_path(@post), class: 'text-muted' %> | <%= link_to "Delete Post", post_path(@post), class: 'text-danger', data: {confirm: 'Are you sure?'}, method: :delete %>
    </div>
</div>
<hr>
<div class="row mb-2">
    <div class="col">
        <!-- Comments partial goes here -->
        <%= render 'comments/comments' %>
        <!-- Comments form goes here -->
        <%= render 'comments/comments-form' %>
    </div>
</div>